# Generated by Django 2.0.5 on 2018-05-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personal_web',
            new_name='personal',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='descrption',
            new_name='description',
        ),
    ]
