# Generated by Django 2.0.5 on 2018-05-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_web', '0002_auto_20180523_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(default='作品标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='personal',
            name='description',
            field=models.CharField(default='在这里写作品的简介', max_length=100),
        ),
    ]
